# Generated by Django 3.1.7 on 2021-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(max_length=200, unique=True)),
                ('byline', models.CharField(default='byline', max_length=1000, unique=True)),
                ('opening_date', models.CharField(default='year', max_length=50)),
                ('headline', models.CharField(default='headline', max_length=2000)),
                ('summary_short', models.TextField(default='summary')),
                ('url', models.CharField(default='default-url', max_length=1000)),
                ('image', models.TextField(default='image')),
            ],
        ),
    ]
